//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLOBALNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class boleta_pago
    {
        public int id_boleta { get; set; }
        public int id_numero { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<decimal> comision { get; set; }
        public Nullable<decimal> cobrado { get; set; }
        public Nullable<decimal> vuelto { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
    
        public virtual numero numero { get; set; }
    }
}
